# Site settings
title: Founders & Coders
email: contact@foundersandcoders.org
description: > # this means to ignore newlines until "baseurl:"
  The Founders & Coders website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.foundersandcoders.org" # the base hostname & protocol for your site
twitter_username: founderscoders
github_username: selforganising

# Build settings
markdown: kramdown
